#!/usr/bin/env python3
"""aclc - the Acl front-end.

Parses a .acl source file with an ANTLR-generated parser and emits textual MLIR
in the `accel` pipeline's input form (func + arith over f32). Feed the output to
accel-opt --fuse-mac to raise the arithmetic into accel.mac.

    .venv/bin/python frontend/aclc.py examples/quadratic.acl
    .venv/bin/python frontend/aclc.py examples/quadratic.acl | \
        build/bin/accel-opt --fuse-mac

This is the classic compiler front-end: lexer/parser (ANTLR) -> AST walk ->
IR generation (MLIR).
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "gen"))

from antlr4 import CommonTokenStream, FileStream, InputStream
from antlr4.error.ErrorListener import ErrorListener

from AclLexer import AclLexer
from AclParser import AclParser
from AclVisitor import AclVisitor


class _Raise(ErrorListener):
    def syntaxError(self, recognizer, offendingSymbol, line, col, msg, e):
        raise SystemExit(f"aclc: syntax error at line {line}:{col}: {msg}")


def _fmt(value: float) -> str:
    return f"{value:.6e}"


class MlirEmitter(AclVisitor):
    """Walks the parse tree and emits textual MLIR for each function."""

    def __init__(self):
        self.lines = []     # body lines for the current function
        self.n = 0          # SSA temporary counter
        self.params = set()

    def _tmp(self) -> str:
        name = f"%{self.n}"
        self.n += 1
        return name

    # program : function+ EOF
    def visitProgram(self, ctx):
        out = []
        for fn in ctx.function():
            out.append(self.visitFunction(fn))
        return "\n\n".join(out)

    # function : 'def' ID '(' params? ')' '=' expr ';'
    def visitFunction(self, ctx):
        name = ctx.ID().getText()
        names = []
        if ctx.params():
            names = [p.getText() for p in ctx.params().ID()]
        self.lines, self.n, self.params = [], 0, set(names)

        result = self.visit(ctx.expr())

        sig = ", ".join(f"%{p}: f32" for p in names)
        header = f"func.func @{name}({sig}) -> f32 {{"
        body = "\n".join(f"  {ln}" for ln in self.lines)
        ret = f"  return {result} : f32"
        return "\n".join([header, body, ret, "}"]) if body else \
               "\n".join([header, ret, "}"])

    def _binary(self, ctx, table):
        lhs = self.visit(ctx.expr(0))
        rhs = self.visit(ctx.expr(1))
        mnemonic = table[ctx.op.text]
        dst = self._tmp()
        self.lines.append(f"{dst} = {mnemonic} {lhs}, {rhs} : f32")
        return dst

    def visitMulDivExpr(self, ctx):
        return self._binary(ctx, {"*": "arith.mulf", "/": "arith.divf"})

    def visitAddSubExpr(self, ctx):
        return self._binary(ctx, {"+": "arith.addf", "-": "arith.subf"})

    def visitParenExpr(self, ctx):
        return self.visit(ctx.expr())

    def visitNumberExpr(self, ctx):
        dst = self._tmp()
        self.lines.append(f"{dst} = arith.constant {_fmt(float(ctx.getText()))} : f32")
        return dst

    def visitVarExpr(self, ctx):
        name = ctx.getText()
        if name not in self.params:
            raise SystemExit(f"aclc: unknown variable '{name}'")
        return f"%{name}"


def compile_source(stream) -> str:
    lexer = AclLexer(stream)
    lexer.removeErrorListeners(); lexer.addErrorListener(_Raise())
    parser = AclParser(CommonTokenStream(lexer))
    parser.removeErrorListeners(); parser.addErrorListener(_Raise())
    tree = parser.program()
    return MlirEmitter().visitProgram(tree)


def main(argv):
    if len(argv) < 2:
        sys.exit("usage: aclc.py <input.acl> [-o out.mlir]")
    stream = FileStream(argv[1], encoding="utf-8")
    mlir = compile_source(stream)
    banner = f"// generated by aclc from {os.path.basename(argv[1])}\n"
    if len(argv) >= 4 and argv[2] == "-o":
        with open(argv[3], "w") as f:
            f.write(banner + mlir + "\n")
    else:
        print(banner + mlir)


if __name__ == "__main__":
    main(sys.argv)
